// See: https://www.npmjs.com/package/node-libs-browser

// The list of node core libs (all off by default)
const allOff = {
  assert: false,
  buffer: false,
  child_process: false,
  cluster: false,
  console: false,
  constants: false,
  crypto: false,
  dgram: false,
  dns: false,
  domain: false,
  events: false,
  fs: false,
  http: false,
  https: false,
  module: false,
  net: false,
  os: false,
  path: false,
  punycode: false,
  process: false,
  querystring: false,
  readline: false,
  repl: false,
  stream: false,
  _stream_duplex: false,
  _stream_passthrough: false,
  _stream_readable: false,
  _stream_transform: false,
  _stream_writable: false,
  string_decoder: false,
  sys: false,
  timers: false,
  tls: false,
  tty: false,
  url: false,
  util: false,
  vm: false,
  zlib: false,
};

// The node core libs for in browser usage
export const nodeLibsBrowser = {
  ...allOff,
  global: true,
  process: true,
};
